baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xiangxi.work" # the base hostname & protocol for your site, e.g. http://example.com
logo: logo.png
language: zh-CN # the main language of your site, e.g. en-US
timezone: Asia/Shanghai # the time zone of your site.
destination: ./build # to use github actions to build site

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

words_per_minute: 450 # the number of words per minute. 20260312

minima:
  date_format: "%Y年%-m月%-d日"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

donation:
  enable: true
  afdian: https://ifdian.net/order/create?user_id=a89f0a944e0f11f1848152540025c377
  paypal: https://paypal.me/xiangxismile/
  text_zh: "如果我的想法对你有所启发，欢迎请我喝杯咖啡。☕️"
  text_en: "If you found my thoughts helpful, consider buying me a coffee. ☕️"

sass:
  sass_dir: _sass
  style: compressed

title: 向西笔记
subtitle: "向西的个人空间｜内容创作者 & 独立博客"
description: "向西笔记是由外企人、B站Up主向西运营的个人博客。专注分享沟通技巧、深度书评、高质量商品推荐与好物指南。在这里，陪你一起持续学习、高效生活，探索随时开启旅居的多元生活方式。"
author:
  name: 向西
social:
  github: xiangxinotes