baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xiangxinotes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: zh-CN # the main language of your site, e.g. en-US
timezone: Asia/Shanghai # the time zone of your site.
destination: ./build # to use github actions to build site

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page/:num"

words_per_minute: 450 # the number of words per minute. 20260312

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty



sass:
  sass_dir: _sass
  style: compressed

title: 向西笔记 - 向西 ｜内容创作者、Up主、外企人、旅居专家和法语新手
description: 向西是一名B站Up主、博客主，外企工作8年，在7个城市旅居，向西笔记包含英语和法语的学习经验，包括单词的不同之处分析和学习工具，助你高效而又精准地使用单词；向西笔记还提供旅游攻略、旅居行动指南、不同城市的旅居体验和让你随时开启旅居生活的商品，让你少走弯路，选择最适合你的商品。
author:
  name: 向西
social:
  github: xiangxinotes