#-------------------------------
# General Site Settings
title: 向西笔记 - 内容创作者、Up主、外企工作者、旅居专家和法语新手
logo: logo.png # You can add own logo.
description: 向西是一名B站Up主、博客主，外企工作8年，在7个城市旅居，向西笔记分享英语、法语学习经验，旅居行动指南、不同城市的旅居体验和让你随时开启旅居生活的商品。


#-------------------------------
# Author Settings
author:
  name: 向西
  image: me.jpg
  say-hello: 你好，我是<a href="/about?utm_source=blog&utm_medium=hero_content"><strong>向西</strong></a>
  bio: 向西结合自身经历经验，为你提供<a href="/tag/product?utm_source=blog&utm_medium=hero_content"><strong>商品推荐</strong></a>、<a href="/tag/sojourn?utm_source=blog&utm_medium=hero_content"><strong>旅居建议</strong></a>和<strong>工作建议</strong>，分享<a href="/tag/interview?utm_source=blog&utm_medium=hero_content">面试技巧</a>、<a href="/tag/languages?utm_source=blog&utm_medium=hero_content"><strong>语言学习技巧和工具</strong></a>、<a href="/tag/travel?utm_source=blog&utm_medium=hero_content"><strong>旅游经验</strong></a>、书单和让你变幸福的<a href="/tag/tools?utm_source=blog&utm_medium=hero_content">小工具</a>。


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Comment Section (IntenseDebate) For compatible with CN
intensedebate-identifier: 848807791b33d240193718a7e05a0e22 # add your identifier for IntenseDebate Comment. For example 848807791b33d240193718a7e05a0e22


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-XKTXS5QCR2 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Google Search Console
google-site-verification: wmLF-J7xkXz3CNC-3pVWU0CcD3YCSclogsQJrgfqNQ

#-------------------------------
# Google adsense
google-adsense: ca-pub-2729616959486829 # Add your publisher id.

#-------------------------------
# Newsletter
# mailchimp: github.us13.list-manage.com/subscribe/post?u=aea9cafd5d3e466749d1ddf6e&amp;id=10cf18c315&amp;f_id=00b0e4e2f0 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
