#-------------------------------
# Author Settings
author:
  name: 向西
  image: me.webp
  say-hello: 你好，我是<a href="/about"><strong>向西</strong></a>
  bio: 本站<strong>每周六</strong>更新一篇原创文章，所有内容均为亲身经历。<br/>我的使命：<strong>让你带着问题而来，带着解决方案离开。</strong><br/>从<a href="/tag/communication-skills">人际沟通</a>到<a href="/tag/workplace">职场成长</a>，帮你全方位实现<a href="/tag/personal-growth">自我提升</a>。
  cta: 关注我


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
# pinterest: https://linkedin.com/ # Add your LinkedIn handle
weibo: https://m.weibo.cn/u/2689245344
bilibili: https://space.bilibili.com/329955183


#-------------------------------
# My Work Section
works: 
  - name: SQL Wizland
    url: https://sqlwizland.xiangxi.work
  - name: Smile Finder
    url: https://smilefinder.xiangxi.work
  - name: Smile Lab
    url: https://smilelab.xiangxi.work

#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Comment Section (IntenseDebate) For compatible with CN
intensedebate-identifier: 848807791b33d240193718a7e05a0e22 # add your identifier for IntenseDebate Comment. For example 848807791b33d240193718a7e05a0e22


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-XKTXS5QCR2 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Google Search Console
google-site-verification: wmLF-J7xkXz3CNC-3pVWU0CcD3YCSclogsQJrgfqNQ

#-------------------------------
# Google adsense
google-adsense: ca-pub-2729616959486829 # Add your publisher id.

#-------------------------------
# Newsletter
# mailchimp: github.us13.list-manage.com/subscribe/post?u=aea9cafd5d3e466749d1ddf6e&amp;id=10cf18c315&amp;f_id=00b0e4e2f0 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
