#-------------------------------
# General Site Settings
title: 向西笔记
logo: logo.png # You can add own logo.
description: 向西笔记分享让你生活变好的商品、让你变幸福的工具、让你通过面试的技巧、让你从工作中获得更多、让你改变一生的书单、让你旅居顺心的技巧，还帮你做旅游攻略，让你玩儿好。


#-------------------------------
# Author Settings
author:
  name: 向西
  image: me.jpg
  say-hello: 你好，我是<strong>向西</strong>
  bio: 向西结合自身经历经验，为你提供<a href="/tag/product"><strong>商品推荐</strong></a>、<a href="/tag/sojourn"><strong>旅居建议</strong></a>和<strong>工作建议</strong>，分享<a href="/tag/interview"><strong>面试技巧</strong></a>、<strong>旅游经验</strong>、<strong>书单</strong>和让你变幸福的<a href="/tag/tools"><strong>小工具</strong></a>。


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-XKTXS5QCR2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
# mailchimp: github.us13.list-manage.com/subscribe/post?u=aea9cafd5d3e466749d1ddf6e&amp;id=10cf18c315&amp;f_id=00b0e4e2f0 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
