#-------------------------------
# Author Settings
author:
  name: 向西
  image: me.webp
  say-hello: 你好，我是<a href="/about"><strong>向西</strong></a>
  bio: 本站<strong>每周六</strong>更新一篇原创文章，所有内容均为亲身经历。<br/>我的使命：<strong>让你带着问题而来，带着解决方案离开。</strong><br/>从<a href="/tag/communication-skills/">人际沟通</a>到<a href="/tag/workplace/">职场成长</a>，帮你全方位实现<a href="/tag/self-mastery/">自我管理</a>。
  bio-about: 我目前在一家外企任职，有10年<a href="/tag/workplace/">工作经验</a>。<br/>好奇心旺盛，喜欢探索世界。曾在7个城市<a href="/tag/sojourn/">旅居</a>，平时喜欢<a href="/tag/book/">读书</a>、玩桌游、打羽毛球，致力于提升自己。<br/><strong>每周六</strong>会在本站更新一篇日常思考，解决一个问题。
  cta: 关注我


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
# pinterest: https://linkedin.com/ # Add your LinkedIn handle
weibo: https://m.weibo.cn/u/2689245344
bilibili: https://space.bilibili.com/329955183


#-------------------------------
# My Project Section
projects:
  - title: Smile Lab
    description: 专为情感神经可塑性而设计的空间，重新训练大脑，从而获得幸福感。
    url: https://smilelab.xiangxi.work
    date:
    last_modified_at: Wed May 27 10:23:16 2026 +0800
    image: https://smilelab.xiangxi.work/assets/favicon/favicon-96x96.png
    image_alt: Smile Lab的logo，训练大脑的正向思维倾向
  - title: Smile Finder
    description: 以游戏化形式练习正向偏向训练，让思维正向这件事变得更简单。
    url: https://smilefinder.xiangxi.work
    date:
    last_modified_at: Wed Apr 8 17:51:37 2026 +0800
    image:
    image_alt:
  - title: SQL Wizland
    description: 面试前复习SQL语法的工具，提供极简的复习闭环。
    url: https://sqlwizland.xiangxi.work
    date:
    last_modified_at: Sun Mar 8 13:25:14 2026 +0800
    image: https://sqlwizland.xiangxi.work/images/apple-touch-icon.png
    image_alt: SQL Wizland的logo，SQL语法复习网站

#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Comment Section (IntenseDebate) For compatible with CN
intensedebate-identifier: 848807791b33d240193718a7e05a0e22 # add your identifier for IntenseDebate Comment. For example 848807791b33d240193718a7e05a0e22


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-XKTXS5QCR2 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Google Search Console
google-site-verification: wmLF-J7xkXz3CNC-3pVWU0CcD3YCSclogsQJrgfqNQ

#-------------------------------
# Google adsense
google-adsense: ca-pub-2729616959486829 # Add your publisher id.

#-------------------------------
# Newsletter
# mailchimp: github.us13.list-manage.com/subscribe/post?u=aea9cafd5d3e466749d1ddf6e&amp;id=10cf18c315&amp;f_id=00b0e4e2f0 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
